# Stage 1

## Inspect data

In [ ]:
#Set paths
import os

DATA_DIR = "data"   # change if needed
DB_FILE = "lahman_pandas.db"

In [19]:
#List all .csv files
csv_files = [f for f in os.listdir(DATA_DIR) if f.endswith(".csv")]
csv_files

['AwardsManagers.csv',
 'Managers.csv',
 'AwardsPlayers.csv',
 'Fielding.csv',
 'Salaries.csv',
 'Parks.csv',
 'Schools.csv',
 'People.csv',
 'PitchingPost.csv',
 'Teams.csv',
 'Appearances.csv',
 'AwardsSharePlayers.csv',
 'TeamsFranchises.csv',
 'Batting.csv',
 'ManagersHalf.csv',
 'FieldingOF.csv',
 'Pitching.csv',
 'CollegePlaying.csv',
 'HomeGames.csv',
 'HallOfFame.csv',
 'AwardsShareManagers.csv',
 'BattingPost.csv',
 'TeamsHalf.csv',
 'SeriesPost.csv',
 'FieldingPost.csv',
 'AllstarFull.csv',
 'FieldingOFsplit.csv']

In [20]:
#Inspect a sample table
import pandas as pd

people = pd.read_csv(os.path.join(DATA_DIR, "People.csv"))
people.head()

,ID,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,...,nameLast,nameGiven,weight,height,bats,throws,debut,bbrefID,finalGame,retroID
0,1,aardsda01,1981.0,12.0,27.0,Denver,USA,CO,NaN,NaN,...,Aardsma,David Allan,215.0,75.0,R,R,2004-04-06,aardsda01,2015-08-23,aardd001
1,2,aaronha01,1934.0,2.0,5.0,Mobile,USA,AL,2021.0,1.0,...,Aaron,Henry Louis,180.0,72.0,R,R,1954-04-13,aaronha01,1976-10-03,aaroh101
2,3,aaronto01,1939.0,8.0,5.0,Mobile,USA,AL,1984.0,8.0,...,Aaron,Tommie Lee,190.0,75.0,R,R,1962-04-10,aaronto01,1971-09-26,aarot101
3,4,aasedo01,1954.0,9.0,8.0,Orange,USA,CA,NaN,NaN,...,Aase,Donald William,190.0,75.0,R,R,1977-07-26,aasedo01,1990-10-03,aased001
4,5,abadan01,1972.0,8.0,25.0,Palm Beach,USA,FL,NaN,NaN,...,Abad,Fausto Andres,184.0,73.0,L,L,2001-09-10,abadan01,2006-04-13,abada001

In [21]:
#Check columns
people.columns

Index(['ID', 'playerID', 'birthYear', 'birthMonth', 'birthDay', 'birthCity',
       'birthCountry', 'birthState', 'deathYear', 'deathMonth', 'deathDay',
       'deathCountry', 'deathState', 'deathCity', 'nameFirst', 'nameLast',
       'nameGiven', 'weight', 'height', 'bats', 'throws', 'debut', 'bbrefID',
       'finalGame', 'retroID'],
      dtype='str')

In [22]:
#Check dtypes
people.info()

<class 'pandas.DataFrame'>
RangeIndex: 24270 entries, 0 to 24269
Data columns (total 25 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            24270 non-null  int64
 1   playerID      24270 non-null  str
 2   birthYear     23292 non-null  float64
 3   birthMonth    22918 non-null  float64
 4   birthDay      22749 non-null  float64
 5   birthCity     23140 non-null  str
 6   birthCountry  23331 non-null  str
 7   birthState    22909 non-null  str
 8   deathYear     12033 non-null  float64
 9   deathMonth    12026 non-null  float64
 10  deathDay      11929 non-null  float64
 11  deathCountry  11990 non-null  str
 12  deathState    11918 non-null  str
 13  deathCity     11970 non-null  str
 14  nameFirst     23857 non-null  str
 15  nameLast      24270 non-null  str
 16  nameGiven     24270 non-null  str
 17  weight        22088 non-null  float64
 18  height        22262 non-null  float64
 19  bats          21423 non-null  str
 20  throws        22130 non-null  str
 21  debut         21240 non-null  str
 22  bbrefID       22995 non-null  str
 23  finalGame     19338 non-null  str
 24  retroID       23373 non-null  str
dtypes: float64(8), int64(1), str(16)
memory usage: 6.7 MB

In [23]:
#Do this for batting
batting = pd.read_csv(os.path.join(DATA_DIR, "Batting.csv"))
batting.head()

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,aardsda01,2004,1,SFN,NL,11,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,aardsda01,2006,1,CHN,NL,45,2,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
2,aardsda01,2007,1,CHA,AL,25,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,aardsda01,2008,1,BOS,AL,47,1,0,0,0,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
4,aardsda01,2009,1,SEA,AL,73,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
#Check columns
batting.columns

Index(['playerID', 'yearID', 'stint', 'teamID', 'lgID', 'G', 'AB', 'R', 'H',
       '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'IBB', 'HBP', 'SH',
       'SF', 'GIDP'],
      dtype='str')

## Creating Database

In [9]:
#Create the SQLite Database
import sqlite3

conn = sqlite3.connect(DB_FILE)
cursor = conn.cursor()

In [ ]:
#Load all .csv files into SQLite
for file in csv_files:
    table_name = file.replace(".csv", "")
    file_path = os.path.join(DATA_DIR, file)
    
    print(f"Loading {table_name}...")
    
    df = pd.read_csv(file_path)
    
    df.to_sql(
        table_name,
        conn,
        if_exists="replace",
        index=False
    )

print("All tables loaded.")

Loading AwardsManagers...
Loading Managers...
Loading AwardsPlayers...
Loading Fielding...
Loading Salaries...
Loading Parks...
Loading Schools...
Loading People...
Loading PitchingPost...
Loading Teams...
Loading Appearances...
Loading AwardsSharePlayers...
Loading TeamsFranchises...
Loading Batting...
Loading ManagersHalf...
Loading FieldingOF...
Loading Pitching...
Loading CollegePlaying...
Loading HomeGames...
Loading HallOfFame...
Loading AwardsShareManagers...
Loading BattingPost...
Loading TeamsHalf...
Loading SeriesPost...
Loading FieldingPost...
Loading AllstarFull...
Loading FieldingOFsplit...
All tables loaded.

In [11]:
#Verify tables exist
query = """
SELECT name 
FROM sqlite_master 
WHERE type='table'
ORDER BY name;
"""

pd.read_sql(query, conn)

                   name
0           AllstarFull
1           Appearances
2        AwardsManagers
3         AwardsPlayers
4   AwardsShareManagers
5    AwardsSharePlayers
6               Batting
7           BattingPost
8        CollegePlaying
9              Fielding
10           FieldingOF
11      FieldingOFsplit
12         FieldingPost
13           HallOfFame
14            HomeGames
15             Managers
16         ManagersHalf
17                Parks
18               People
19             Pitching
20         PitchingPost
21             Salaries
22              Schools
23           SeriesPost
24                Teams
25      TeamsFranchises
26            TeamsHalf

In [12]:
#Inspect a table schema
#Example: Batting
pd.read_sql("PRAGMA table_info(Batting);", conn)

    cid      name     type  notnull dflt_value  pk
0     0  playerID     TEXT        0       None   0
1     1    yearID  INTEGER        0       None   0
2     2     stint  INTEGER        0       None   0
3     3    teamID     TEXT        0       None   0
4     4      lgID     TEXT        0       None   0
5     5         G  INTEGER        0       None   0
6     6        AB  INTEGER        0       None   0
7     7         R  INTEGER        0       None   0
8     8         H  INTEGER        0       None   0
9     9        2B  INTEGER        0       None   0
10   10        3B  INTEGER        0       None   0
11   11        HR  INTEGER        0       None   0
12   12       RBI     REAL        0       None   0
13   13        SB     REAL        0       None   0
14   14        CS     REAL        0       None   0
15   15        BB  INTEGER        0       None   0
16   16        SO     REAL        0       None   0
17   17       IBB     REAL        0       None   0
18   18       HBP     REAL        0       None   0
19   19        SH     REAL        0       None   0
20   20        SF     REAL        0       None   0
21   21      GIDP     REAL        0       None   0

In [13]:
#Sanity check
#Check that playerID overlaps
pd.read_sql("""
SELECT COUNT(DISTINCT playerID) 
FROM Batting;
""", conn)

   COUNT(DISTINCT playerID)
0                     24011

In [14]:
pd.read_sql("""
SELECT COUNT(DISTINCT playerID) 
FROM People;
""", conn)

   COUNT(DISTINCT playerID)
0                     24270

In [15]:
pd.read_sql("""
SELECT p.nameFirst, p.nameLast, b.yearID, b.HR
FROM Batting b
JOIN People p ON b.playerID = p.playerID
LIMIT 10;
""", conn)

  nameFirst nameLast  yearID  HR
0     David  Aardsma    2004   0
1     David  Aardsma    2006   0
2     David  Aardsma    2007   0
3     David  Aardsma    2008   0
4     David  Aardsma    2009   0
5     David  Aardsma    2010   0
6     David  Aardsma    2012   0
7     David  Aardsma    2013   0
8     David  Aardsma    2015   0
9      Hank    Aaron    1954  13

In [ ]:
#Create most important indices
cursor.execute("CREATE INDEX idx_batting_playerID ON Batting(playerID);")
cursor.execute("CREATE INDEX idx_batting_yearID ON Batting(yearID);")
cursor.execute("CREATE INDEX idx_pitching_playerID ON Pitching(playerID);")
cursor.execute("CREATE INDEX idx_people_playerID ON People(playerID);")

conn.commit()